import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (session) console.log("Successfully signin:", session.user);

  return (
    <>
      <Head>
        <title>Blogster</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="porse">Initial setup</div>
    </>
  );
};

export default Home;
